server:
  port: 2333

spring:
  datasource:
    username: root
    password: bdwdl19981015
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.github.hieheihei.hotel.admin.model

#showSql
logging:
  level:
    com.github.hieheihei.hotel: debug
    
 
